export const AUTH_REPOSITORY_TOKEN = 'AUTH_REPOSITORY_TOKEN';
export const AUTH_IDENTIFIER_REPOSITORY_TOKEN = 'AUTH_IDENTIFIER_REPOSITORY_TOKEN';
export const OAUTH_PROVIDER_REPOSITORY_TOKEN = 'OAUTH_PROVIDER_REPOSITORY_TOKEN';
export const OTP_TOKEN_REPOSITORY_TOKEN = 'OTP_TOKEN_REPOSITORY_TOKEN';
export const MFA_METHOD_REPOSITORY_TOKEN = 'MFA_METHOD_REPOSITORY_TOKEN';
export const SESSION_REPOSITORY_TOKEN = 'SESSION_REPOSITORY_TOKEN';
export const SESSION_LOG_REPOSITORY_TOKEN = 'SESSION_LOG_REPOSITORY_TOKEN';
