export * from './auth/auth.module';
export * from './auth/auth.service';
export { AUTH_MODULE_OPTIONS, AuthModuleOptions } from './auth/interfaces/auth-module-options.interface';
export * from './auth/decorator/current-user.decorator';
export type { AuthCredential } from './auth/interfaces/current-user-interface';
export * from './auth/decorator/public.decorator';
export * from './auth/decorator/optional.decorator';
export * from './auth/enums/auth-type.enum';
export { Auth as TypeOrmAuth } from './database/typeorm/entities/auth.entity';
export { Session as TypeOrmSession } from './database/typeorm/entities/session.entity';
export { MfaMethod as TypeOrmMfaMethod } from './database/typeorm/entities/mfa-method.entity';
export { OAuthProvider as TypeOrmOAuthProvider } from './database/typeorm/entities/oauth-provider.entity';
export { OtpToken as TypeOrmOtpToken } from './database/typeorm/entities/otp-token.entity';
export { BaseEntity as TypeOrmBaseEntity } from './database/typeorm/entities/base.entity';
export * from './auth/dto/requests/login.dto';
export * from './auth/dto/requests/signup.dto';
export * from './auth/dto/requests/refresh-token.dto';
export * from './auth/guards/jwt-auth.guard';
export * from './auth/guards/optional-auth.guard';
export * from './database/typeorm/migrations/auth-schema.initializer';
export * from './database/typeorm/migrations/migration.service';
export * from './auth/enums/auth.events';
export * from './auth/interfaces/models.interface';
export * from './auth/interfaces/auth-notification-provider.interface';
export * from './auth/interfaces/signin-event-body.interface';
export * from './auth/interfaces/signup-event-body.interface';
export * from './auth/interfaces/auth-otp-provider.interface';
export * from './auth/interfaces/repositories.interface';
export * from './auth/interfaces/repository-tokens';

export * from './database/typeorm/typeorm-auth.adapter';
export * from './database/prisma/prisma-auth.adapter';
