export enum OtpPurpose {
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  VERIFY_PHONE = 'VERIFY_PHONE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  LOGIN_2FA = 'LOGIN_2FA',
  MAGIC_LINK = 'MAGIC_LINK',
  SECURE_ACCOUNT = 'SECURE_ACCOUNT',
}
